# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Changes with respect to the base configuration file specified in run->base_config
# default value is config.tutorial.yaml
run:
  name: NG_no_oil  # Name of the configuration (arbitrary string value)
  shared_cutouts: false  # set to true to share the default cutout(s) across runs
  base_config: config.default.yaml  # base configuration file

retrieve_databundle: # required to be "false" for nice CI test output
  show_progress: false

snapshots:
  start: 2013-03-1
  end: 2013-03-7

scenario:
  simpl: ['']
  ll: [copt]
  clusters: [10]
  opts: [Co2L-4H]

countries:
- NG

enable:
  retrieve_databundle: true
  retrieve_cost_data: true
  download_osm_data: true
  # If "build_cutout" : true # requires cds API key https://cds.climate.copernicus.eu/api-how-to
  # More information https://atlite.readthedocs.io/en/latest/introduction.html#datasets
  build_cutout: true
  build_natura_raster: true

electricity:
  conventional_carriers: [nuclear, OCGT, CCGT, lignite, geothermal, biomass]
